### ISSUE TITLE
Indego integration not working after update to HA 2024.11

### ISSUE THREAD

**Issue by wimb0** [sander1988/Indego#251]
## Checklist

- [X] I have updated to the latest available of the Indego component version.
- [X] I have updated to the latest available Home Assistant version.
- [X] I have read the README https://github.com/sander1988/Indego/blob/master/README.md) and especially read the part about the KNOWN ISSUES (https://github.com/sander1988/Indego/blob/master/README.md#known-issues).
- [X] I have checked hecked for other open or recently closed issues for similar bugs/issues.

## The problem

Indego Integration does not start on Home Assistant 2024.11

## Expected behavior

A working integration

## Steps to reproduce

Update to HA 2024.11

## Environment

- Indego component release with the issue: 5.7.5
- Last working Indego component release (if known):5.7.5
- Home Assistant release with the issue: 2024.11.0
- Last working Home Assistant release (if known): 2024.10.3
- Operating system: HOAS VM on Proxmox

## Logs

```yaml
Logger: homeassistant.config_entries
Bron: config_entries.py:3227
Eerst voorgekomen: 09:28:40 (3 gebeurtenissen)
Laatst gelogd: 09:28:51

Error occurred loading flow for integration indego: cannot import name 'DATA_STORAGE' from 'homeassistant.components.application_credentials' (/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py)
```
```yaml
Logger: homeassistant.config_entries
Bron: config_entries.py:604
Eerst voorgekomen: 09:21:30 (2 gebeurtenissen)
Laatst gelogd: 09:24:22

Error importing platform config_flow from integration indego to set up indego configuration entry: cannot import name 'DATA_STORAGE' from 'homeassistant.components.application_credentials' (/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py)
```
```yaml
Logger: homeassistant.util.loop
Bron: util/loop.py:136
Eerst voorgekomen: 09:24:22 (1 gebeurtenissen)
Laatst gelogd: 09:24:22

Detected blocking call to import_module with args ('custom_components.indego.config_flow',) inside the event loop by integration 'config' at homeassistant/components/config/config_entries.py, line 120: await hass.config_entries.async_reload(entry_id) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1300: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 120, in post await hass.config_entries.async_reload(entry_id)
```

## Additional information

Tried removing and re-installing the integration, but that throws the same errors as above.
